//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Course.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UUU20010101
    {
        public Nullable<System.Guid> UNIQ_KEY { get; set; }
        public string CORP_NO { get; set; }
        public string PROD_NO { get; set; }
        public string PROD_NAME_CHI { get; set; }
        public string PROD_NAME_ENG { get; set; }
        public string PROD_NAME_CHI_SECRET { get; set; }
        public string PROD_ABBR_CHI { get; set; }
        public string PROD_ABBR_ENG { get; set; }
        public string PROD_NAME_INVO { get; set; }
        public string PROD_SCALE_DESC { get; set; }
        public string PROD_TYPE { get; set; }
        public string PROD_KIND_CODE { get; set; }
        public string PROD_GRADE_CODE { get; set; }
        public string PROD_BRAND { get; set; }
        public string ISBN_ISSN_CODE { get; set; }
        public string MODEL_CODE { get; set; }
        public string ORI_CORP_CODE { get; set; }
        public string BAR_CODE { get; set; }
        public string CCC_CODE { get; set; }
        public string CIS_CODE { get; set; }
        public string LAW_ARTICLE { get; set; }
        public string ACCT_TYPE_CODE { get; set; }
        public string PROD_NO_TAX_YN { get; set; }
        public string PROD_EXPECT_STORE_NO { get; set; }
        public string PROD_EXPECT_STORE_POSITION { get; set; }
        public string PROD_STORE_YN { get; set; }
        public string BATCH_NUMBER_CONTROL_YN { get; set; }
        public string MACHINE_YN { get; set; }
        public string ABC_LEVEL { get; set; }
        public string PROD_IMPORT_GRADE_CODE { get; set; }
        public string MAJOR_PACKAGING { get; set; }
        public Nullable<decimal> MAJOR_PACKAGING_QTY { get; set; }
        public string MAJOR_PACKING_CODE { get; set; }
        public Nullable<decimal> PROD_PACKAGE_QTY { get; set; }
        public Nullable<decimal> PROD_CARRYING_COST_PER { get; set; }
        public string GROUP_YN { get; set; }
        public string PROD_PE_MUST_CODE { get; set; }
        public Nullable<int> NO_MOVE_DEFAULT_DAYS { get; set; }
        public string PROD_DISCOUNT_CODE { get; set; }
        public string REMARK { get; set; }
        public string PROD_KIND_1_CODE { get; set; }
        public string PROD_KIND_2_CODE { get; set; }
        public string PROD_KIND_3_CODE { get; set; }
        public string PROD_KIND_4_CODE { get; set; }
        public string PROD_KIND_5_CODE { get; set; }
        public string PROD_KIND_6_CODE { get; set; }
        public string PROD_KIND_7_CODE { get; set; }
        public string PROD_KIND_8_CODE { get; set; }
        public string PROD_KIND_9_CODE { get; set; }
        public string PROD_KIND_10_CODE { get; set; }
        public string QC_YN { get; set; }
        public string CHECK_LIST_PRODUCE_TYPE_CODE { get; set; }
        public string PART_FULL_TYPE { get; set; }
        public string TEST_RESULT_RECORD_TYPE_CODE { get; set; }
        public Nullable<decimal> PROD_CHECK_DAY { get; set; }
        public string TEST_CYCLE_MM_DAY_TYPE_CODE { get; set; }
        public Nullable<int> TEST_CYCLE_MM_OR_DD { get; set; }
        public string TAKE_STOCK_CYCLE_CODE { get; set; }
        public string TEST_ITEM_FORM { get; set; }
        public string TEST_STAND_NO_SECRET { get; set; }
        public string PROD_MAIN_SALE_DEPT_NO { get; set; }
        public string OUT_OF_STOCK_REASON_CODE { get; set; }
        public Nullable<System.DateTime> LAUNCH_DATE { get; set; }
        public Nullable<System.DateTime> BEG_DATE { get; set; }
        public Nullable<System.DateTime> PROD_LIMIT_DATE { get; set; }
        public string INDE_NO { get; set; }
        public string BUSINESS_ITEM_CODE { get; set; }
        public string PROD_SCALE_NO_YN { get; set; }
        public string PROD_SCALE_NO_FORMAT_CODE { get; set; }
        public string BONDED_GOODS_YN { get; set; }
        public Nullable<decimal> CHECK_ALLOW_RATE { get; set; }
        public string BOM_NO_FINISHED { get; set; }
        public string AUTHOR_NAMES { get; set; }
        public string TRANSLATOR_NAMES { get; set; }
        public string WRITE_MUSIC_NAMES { get; set; }
        public string WRITE_WORDS_NAMES { get; set; }
        public string LEAD_SINGER_NAMES { get; set; }
        public string PUBLISH_CORP { get; set; }
        public string GENERAL_MARKET_CORP { get; set; }
        public Nullable<System.DateTime> ISSUING_DATE { get; set; }
        public string CLOSE_YN { get; set; }
        public Nullable<System.DateTime> STOP_USE_DATE { get; set; }
        public string DEL_YN { get; set; }
        public string LIMITS_OF_AUTHORITY_CODE { get; set; }
        public string PROD_CLEARING_YN { get; set; }
        public Nullable<System.DateTime> CLEARING_MARK_DATE { get; set; }
        public string PROD_SHARE_YN { get; set; }
        public string DEPT_BOSS_ALLOW_YN { get; set; }
        public string DEPT_BOSS_ALLOW_ID { get; set; }
        public Nullable<System.DateTime> DEPT_BOSS_ALLOW_DATE { get; set; }
        public string ENTRY_ID { get; set; }
        public Nullable<System.DateTime> ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
        public string ENTRY_TYPE { get; set; }
        public string USC_FIELD_CHA_1 { get; set; }
        public string USC_FIELD_CHA_2 { get; set; }
        public string USC_FIELD_CHA_3 { get; set; }
        public string USC_FIELD_CHA_4 { get; set; }
        public string USC_FIELD_CHA_5 { get; set; }
        public string USC_FIELD_CHA_6 { get; set; }
        public string USC_FIELD_CHA_7 { get; set; }
        public string USC_FIELD_CHA_8 { get; set; }
        public string USC_FIELD_CHA_9 { get; set; }
        public string USC_FIELD_CHA_10 { get; set; }
        public Nullable<decimal> USC_FIELD_NUM_1 { get; set; }
        public Nullable<decimal> USC_FIELD_NUM_2 { get; set; }
        public Nullable<System.DateTime> USC_FIELD_DATE_1 { get; set; }
        public Nullable<System.DateTime> USC_FIELD_DATE_2 { get; set; }
        public string FIELD_CHA_1 { get; set; }
        public string FIELD_CHA_2 { get; set; }
        public string FIELD_CHA_3 { get; set; }
        public string FIELD_CHA_4 { get; set; }
        public string FIELD_CHA_5 { get; set; }
        public string FIELD_CHA_6 { get; set; }
        public string FIELD_CHA_7 { get; set; }
        public string FIELD_CHA_8 { get; set; }
        public string FIELD_CHA_9 { get; set; }
        public string FIELD_CHA_10 { get; set; }
        public string VOUCHXX_FIELD_CHA_1 { get; set; }
        public string VOUCHXX_FIELD_CHA_2 { get; set; }
        public string VOUCHXX_FIELD_CHA_3 { get; set; }
        public string VOUCHXX_FIELD_CHA_4 { get; set; }
        public string VOUCHXX_FIELD_CHA_5 { get; set; }
        public string VOUCHXX_FIELD_CHA_6 { get; set; }
        public string VOUCHXX_FIELD_CHA_7 { get; set; }
        public string VOUCHXX_FIELD_CHA_8 { get; set; }
        public string VOUCHXX_FIELD_CHA_9 { get; set; }
        public string VOUCHXX_FIELD_CHA_10 { get; set; }
        public string VOUCHXX_FIELD_CHA_11 { get; set; }
        public string VOUCHXX_FIELD_CHA_12 { get; set; }
        public string VOUCHXX_FIELD_CHA_13 { get; set; }
        public string VOUCHXX_FIELD_CHA_14 { get; set; }
        public string VOUCHXX_FIELD_CHA_15 { get; set; }
        public string VOUCHXX_FIELD_CHA_16 { get; set; }
        public Nullable<decimal> VOUCHXX_FIELD_NUM_1 { get; set; }
        public Nullable<decimal> VOUCHXX_FIELD_NUM_2 { get; set; }
        public Nullable<decimal> VOUCHXX_FIELD_NUM_3 { get; set; }
        public Nullable<decimal> VOUCHXX_FIELD_NUM_4 { get; set; }
        public Nullable<decimal> VOUCHXX_FIELD_NUM_5 { get; set; }
        public Nullable<decimal> VOUCHXX_FIELD_NUM_6 { get; set; }
        public Nullable<decimal> VOUCHXX_FIELD_NUM_7 { get; set; }
        public Nullable<decimal> VOUCHXX_FIELD_NUM_8 { get; set; }
        public Nullable<System.DateTime> VOUCHXX_FIELD_DATE_1 { get; set; }
        public Nullable<System.DateTime> VOUCHXX_FIELD_DATE_2 { get; set; }
        public Nullable<System.DateTime> VOUCHXX_FIELD_DATE_3 { get; set; }
        public Nullable<System.DateTime> VOUCHXX_FIELD_DATE_4 { get; set; }
        public Nullable<System.DateTime> VOUCHXX_FIELD_DATE_5 { get; set; }
        public Nullable<System.DateTime> VOUCHXX_FIELD_DATE_6 { get; set; }
        public Nullable<System.DateTime> VOUCHXX_FIELD_DATE_7 { get; set; }
        public Nullable<System.DateTime> VOUCHXX_FIELD_DATE_8 { get; set; }
        public string CAP_PER_UNIFY_CODE { get; set; }
        public string PUR_EQUAL_QTY_YN { get; set; }
        public string ORI_PLACE { get; set; }
        public string PROD_DEPT_NO { get; set; }
        public string VALID_YMD_TYPE { get; set; }
        public Nullable<decimal> VALID_YEARS { get; set; }
        public Nullable<decimal> VALID_MONTHS { get; set; }
        public Nullable<decimal> VALID_DAYS { get; set; }
        public Nullable<decimal> VALID_COUNT_DAYS { get; set; }
        public Nullable<decimal> TASTING_DAYS { get; set; }
        public Nullable<decimal> MAX_QTY { get; set; }
        public string SALE_PE_MUST_CODE { get; set; }
        public string DESIGN_PROD_SHEET { get; set; }
        public string PROD_KIND_SIGN_CODE { get; set; }
        public string PROD_KIND_POS_CODE { get; set; }
        public string BATCH_NUMBER_VIRTUAL_YN { get; set; }
    }
}
